spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: corpabuilder

# App Properties
security:
  jwtSecret: y*f3&B?HXygcPesnr^5-G
  jwtExpirationMs: 86400000

logging:
  level:
    root: DEBUG

server:
  error:
    include-stacktrace: never

components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes